### ISSUE TITLE
New example on how to create a custom StdfRecord

### ISSUE THREAD

**Issue by miguelmpn** [marklio/LinqToStdf#7]
Hello guys,

I'm using your library, but I need to write some custom StdfRecords. There is no example on how to write a new file based on a custom StdfRecord.

I already created one new Record, extending StdfRecords, but when I try to write the file it says `The type CustomTestRecord has no registered unconverter.`

Is it possible to add a simple example on how to do this? I'm only interested in creating new STDF files according to my test spec.

**Comment by marklio** [comment]
The library needs to know how to serialize your type instance into an STDF-formatted record. Due to historical reasons, this is known as "un-converting". There are 2 ways to do this:

* Decorate the type with attributes that describe the in-file structure.
* Implement an unconverter programmatically and registering with the converter factory.

The attributes are intended to be the "easy" way to do this. If you can share your type, and the intended record structure, and can help you with the right approach. You can also look at the attributes on the built-in records.

**Comment by miguelmpn** [comment]
Thank you for your reply.
Actually I've seen that I should rather adapt my results into the standard STDF V4 objects. This is the propper way to work, there is not really a necessity to create a new StdfRecord.
